### ISSUE TITLE
Hello，关于贵实验室的相关问题想请教一下

### ISSUE THREAD

**Issue by paulzhn** [zhangfuli/zhangfuli.github.io#2]
Hello，我本科就读于北京交通大学，在南大软院看到了你们实验室的年度报告，感觉是个很有趣的地方！但是没有找到你的联系方式，就只好通过issue来联系你了，不知道是否方便交流一下呢？我的微信号是dGlhbnhpbjg0MzE= （base64），十分感谢！

**Comment by zhangfuli** [comment]
我加不上，你加我微信吧18851751795
